language: cpp

os:
  - linux

dist: trusty

compiler:
  - clang
  - gcc

sudo: required

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.8
      - g++-5
      - gcc-5
      - cmake
      - pkg-config
      - libhidapi-dev
      - libgtk-3-dev
      - libudev-dev
      - libjsoncpp-dev

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/boost-1.59.0

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5" TOOLSET="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8" CC="clang-3.8" TOOLSET="clang"; fi
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  - |
    BOOST_DIR=${DEPS_DIR}/boost-${BOOST_VERSION}
    if [[ -z "$(ls -A ${BOOST_DIR})" ]]; then
      BOOST_URL="http://sourceforge.net/projects/boost/files/boost/${BOOST_VERSION}/boost_${BOOST_VERSION//\./_}.tar.gz"
      mkdir -p ${BOOST_DIR}
      { travis_retry wget --quiet -O - ${BOOST_URL} | tar --strip-components=1 -xz -C ${BOOST_DIR}; } || exit 1
      (cd ${BOOST_DIR}/tools/build && ./bootstrap.sh && ./b2 install --prefix=${DEPS_DIR}/b2)
      export PATH=${DEPS_DIR}/b2/bin:${PATH}
      (cd ${BOOST_DIR} && b2 toolset=${TOOLSET} --with-filesystem --with-program_options --with-test --with-system stage)
    fi
    CMAKE_OPTIONS+=" -DBOOST_ROOT=${BOOST_DIR}"

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build
  - cd build
  - cmake .. ${CMAKE_OPTIONS} && make

env:
  global:
    - LANG="en_US.UTF-8"
    - BOOST_VERSION=1.59.0
